Repository cisagov/manage.get.gov, pull requests merged in 2023-12, with the labels that each got.

#1490 Issue #1082 - Update AO examples in request flow
  src/registrar/templates/includes/ao_example.html
  src/registrar/tests/test_views.py
Labels: content

#1515 ISSUE #843: Authorizing Official Removal of middle name, phone #
  src/registrar/forms/application_wizard.py
  src/registrar/forms/domain.py
  src/registrar/templates/application_authorizing_official.html
  src/registrar/templates/domain_authorizing_official.html
  src/registrar/tests/test_forms.py
  src/registrar/tests/test_views.py
Labels: dev

#1499 (on getgov-za) Ticket #1450: No name for invitation email bug
  src/registrar/templates/emails/domain_invitation.txt
  src/registrar/tests/test_views.py
  src/registrar/views/domain.py
Labels: bug

#1520 (On getgov-za) Ticket #1456: Table sorting not working correctly
  src/registrar/admin.py
  src/registrar/tests/common.py
  src/registrar/tests/test_admin.py
  src/registrar/tests/test_models.py
  src/registrar/views/utility/mixins.py
Labels: design-review
