Repository cisagov/manage.get.gov, pull requests merged in 2024-08, with the labels that each got.

#2472 Issue #2406: Clipboard Functionality [backup]
  src/package-lock.json
  src/package.json
  src/registrar/assets/js/get-gov-admin.js
  src/registrar/assets/sass/_theme/_admin.scss
  src/registrar/assets/sass/_theme/_buttons.scss
  src/registrar/assets/sass/_theme/_links.scss
  src/registrar/assets/sass/_theme/styles.scss
  src/registrar/templates/admin/change_form.html
  src/registrar/templates/admin/change_form_object_tools.html
  src/registrar/templates/admin/input_with_clipboard.html
  src/registrar/templates/django/admin/includes/contact_detail_list.html
  src/registrar/templates/django/admin/includes/detail_table_fieldset.html
  src/registrar/tests/test_admin.py
  src/registrar/tests/test_admin_domain.py
  src/registrar/tests/test_admin_request.py
Labels: carryover

#2486 2398: Complete manual deploy workflow 2/2
  .github/workflows/deploy-manual.yaml
  docs/operations/README.md
  ops/scripts/create_dev_sandbox.sh
  ops/scripts/destroy_dev_sandbox.sh
Labels: carryover

#2487 Link to new FSM diagram in developer README
  docs/developer/README.md
Labels: carryover

#2538 #2322 Stop Election Office from unlocking early
  src/registrar/models/utility/generic_helper.py
  src/registrar/tests/test_models.py
Labels: carryover

#2412 Issue #2249 - Rebuild DB workflow [forked branch - limited access]
  docs/developer/migration-troubleshooting.md
Labels: carryover

#2599 Adding Team OOO spreadsheet to designer onboarding template
  .github/ISSUE_TEMPLATE/designer-onboarding.md
Labels: onboarding

#2537 Issue #2240 - Registrar step completion bug [backup]
  src/registrar/forms/domain_request_wizard.py
  src/registrar/models/domain_information.py
  src/registrar/models/domain_request.py
  src/registrar/tests/test_forms.py
  src/registrar/tests/test_views_request.py
  src/registrar/views/domain_request.py
Labels: carryover

#2610 Issue #2518: Suborganization shows all related domains/requests [cb]
  src/registrar/admin.py
  src/registrar/templates/django/admin/suborg_change_form.html
Labels: Review Priority🥇

#2598 Issue #2470 - Enhance analysts ability to update "Action needed" email text [nl]
  src/registrar/admin.py
  src/registrar/assets/js/get-gov-admin.js
  src/registrar/assets/sass/_theme/_admin.scss
  src/registrar/templates/django/admin/includes/detail_table_fieldset.html
Labels: Review Priority🥇
