Repository cisagov/manage.get.gov, pull requests merged in 2025-09, with the labels that each got.

#4105 #4075: Update organization overview and organization page - [bob]
  src/registrar/templates/includes/summary_item.html
  src/registrar/templates/portfolio_organization_info.html
  src/registrar/tests/test_views_portfolio.py
  src/registrar/views/portfolios.py
Labels: design-review

#4113 4006: Convert DNS prototype to desired service structure
  docs/developer/README.md
  src/docker-compose.yml
  src/registrar/config/settings.py
  src/registrar/services/cloudflare_service.py
  src/registrar/services/dns_host_service.py
  src/registrar/templates/prototype_domain_dns.html
  src/registrar/tests/services/__init__.py
  src/registrar/tests/services/test_cloudflare_service.py
  src/registrar/tests/services/test_dns_host_service.py
  src/registrar/tests/test_api_helpers.py
  src/registrar/utility/api_helpers.py
  src/registrar/utility/errors.py
  src/registrar/views/domain.py
Labels: Feature: :globe_with_meridians: DNS Hosting

#4145 Change title case to sentence case in registrar [product]
  src/registrar/templates/domain_renewal.html
  src/registrar/templates/domain_request_form.html
  src/registrar/templates/domain_request_intro.html
  src/registrar/templates/domain_senior_official.html
  src/registrar/templates/includes/footer.html
  src/registrar/templates/portfolio_no_requests.html
Labels: design-review

#4185 #4182: Script to fix the stale records [dg]
  src/clone_to_local.sh
  src/registrar/management/commands/clean_up_pii.py
  src/registrar/management/commands/restore_approved_requests.py
Labels: dev

#4072 Changing "member access" to "member role" in admin [potato]
  src/registrar/admin.py
Labels: content
